<template>
  <div>
    <nav class="navbar text-center">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <router-link to="/" active-class="active" tag="li"><a>Home</a></router-link>
          <router-link to="/Home/Resources" tag="li"><a>Back</a></router-link>
        </ul>
      </div>
    </nav>

    <div class="container">
      <div class="table-responsive">
        <table class="table">
      <tr>
        <td width="658" align="center" class="remove"><h2>Sunridge<a name="top"></a> Protective and Restrictive Covenants  <font size="-1">(continued)</font></h2>
          <p>Page 13</p></td>
      </tr>
      <tr>
        <td width="658" align="center">~ ARTICLE VIII (continued)~</td>
      </tr>
      <tr>
        <td width="658" align="justify">8.05&nbsp;&nbsp;&nbsp;<span class="underlining">Late
				    Fees</span>.
          Should any Lot Owner fail to pay the Annual Assessment by the
          designated deadline, the deliquent payment shall be subject
          to a late fee of $20.00 per month until the sum total of
          the Assessment and the cumulated late fees are paid in full.</td>
      </tr>
      <tr>
        <td td width="658" align="justify">8.06&nbsp;&nbsp;&nbsp;<span class="underlining">Extension
				    of Deadline</span>.			    An extension of the date for payment
          of the Annual Assessment of up to two(2) months may be requested
          in writing to the Sunridge Treasurer prior to one week before
          the designated deadline. When written approval is granted,
          a one-time late fee of $10.00 shall be charged for the extension
          period. Should the total payment not be completed by the
          end of the extension period, the additional regular late
          fees will immediately begin to accrue.</td>
      </tr>
      <tr>
        <td align="justify">8.07&nbsp;&nbsp;&nbsp;<span class="underlining">Special
				    Assessement for Catastrophic Damage or Repairs</span>.			    In
          addition to the Annual Assessments provided for above, the
          Association may levy Special Assessments for the purpose
          of defraying any expenses not reasonably capable of being
          fully paid with funds generated by Annual Assessments; or
          the cost of any construction, reconstruction or unexpectedly
          required repair or replacement of an improvement, or of any
          improvement which is required to be maintained by the Association.
          The Association shall give written notice to Owners as to
          the amount of any Special Assessment against each Lot, setting
          forth the total amount of such assessment and the date or
          dates on which the same or installments thereof are due and
          payable. Late fees and extension of deadlines as outlined
          in Paragraph 8.06 shall also apply for Special Assessments.</td>
      </tr>
      <tr>
        <td align="justify">8.08&nbsp;&nbsp;&nbsp;<span class="underlining">Lien
				    for Overdue Assessments</span>.			    All expenses assessed by
          the Association against any Lot, including late fees and
          costs of collection, constitute a lien against the Lot in
          favor of the Association. This paragraph constitutes notice
          to all Lot Owners, purchasers or lenders that a lien exists
          for all current or past due expenses or assessments. Recording
          a notice of lien shall not be necessary to create or perfect
          this lien. The Association may also record with the Weber
          County Recorder a notice of lien against any Lot which is
          not current in the payment of assessments or expenses. The
          lien for past due expenses or assessments may be enforced
          by foreclosure of the Lot Owner's interest or by filing an
          action in court in the same manner as foreclosures of deeds
          of trust, or by filing an action in court, or in any other
          manner permitted by law. The delinquent Lot Owner shall pay
          Association costs, expenses and reasonable attorney fees
          in any foreclosure, court action, or collection effort.</td>
      </tr>
      <tr>
        <td align="justify">8.09&nbsp;&nbsp;&nbsp;<span class="underlining">Liability
				    of Purchaser</span>.			    A purchaser of a Lot shall be jointly
          and severely liable with the seller thereof for all unpaid
          assessments agianst such Lot up to the time of the grant
          or conveyance; provided, however, that the provisions of
          this paragraph shall not prejudice such purchaser's right
          to recover from such seller the amount paid by the purchaser
          for such assessments.</td>
      </tr>
      <tr>
        <td></td>
      </tr>
      <tr>
        <td align="center">ARTICLE IX</td>
      </tr>
      <tr>
        <td align="center">ASSOCIATION INSURANCE AND TAXES</td>
      </tr>
      <tr>
        <td align="justify">9.01&nbsp;&nbsp;&nbsp;<span class="underlining">Public
				    Liability Insurance.</span>  The Association shall obtain and maintain
          at all times a broad form of comprehensive liability insurance
          coverage, in such amounts and in such forms as the Association
          deems advisable to provide adequate protection fo the Association
          and its Board of Trustees.</td>
      </tr>
      <tr>
        <td align="center" bgcolor="#E5E5E5" class="remove"><em>Protective and Restrictive Covenants: Page 13</em></td>
      </tr>
      <tr>
        <td colspan="4" align="center" class="remove">
          <router-link to="/Home/Resources/Cov1" active-class="active"><a>1</a></router-link>&nbsp;&nbsp;
          <router-link to="/Home/Resources/Cov2"><a>2</a></router-link>&nbsp;&nbsp;
          <router-link to="/Home/Resources/Cov3"><a>3</a></router-link>&nbsp;&nbsp;
          <router-link to="/Home/Resources/Cov4"><a>4</a></router-link>&nbsp;&nbsp;
          <router-link to="/Home/Resources/Cov5"><a>5</a></router-link>&nbsp;&nbsp;
          <router-link to="/Home/Resources/Cov6"><a>6</a></router-link>&nbsp;&nbsp;
          <router-link to="/Home/Resources/Cov7"><a>7</a></router-link>&nbsp;&nbsp;
          <router-link to="/Home/Resources/Cov8"><a>8</a></router-link>&nbsp;&nbsp;
          <router-link to="/Home/Resources/Cov9"><a>9</a></router-link>&nbsp;&nbsp;
          <router-link to="/Home/Resources/Cov10"><a>10</a></router-link>&nbsp;&nbsp;
          <router-link to="/Home/Resources/Cov11"><a>11</a></router-link>&nbsp;&nbsp;
          <router-link to="/Home/Resources/Cov12"><a>12</a></router-link>&nbsp;&nbsp;
          13&nbsp;&nbsp;
          <router-link to="/Home/Resources/Cov14"><a>14</a></router-link>&nbsp;&nbsp;
          <router-link to="/Home/Resources/Cov15"><a>15</a></router-link></td>
      </tr>
      <tr>
        <td colspan="4" class="remove"><a href="#top">Go to top of page</a></td>
      </tr>
    </table>
  </div>
    </div>
  </div>
</template>
