import Home from './components/Home.vue'
import Image from './assets/photos/Photos.vue'
import Member from './components/Board.vue'
import Attention from './components/Attention.vue'
import Maps from './components/Map.vue'
import Calender from './assets/Calander.vue'
import Classified from './assets/Classified.vue'
import Resource from  './assets/resources/Resources.vue'
import Cov1 from './assets/resources/Covenants/Covenant1.vue'
import Cov2 from './assets/resources/Covenants/Covenant2.vue'
import Cov3 from './assets/resources/Covenants/Covenant3.vue'
import Cov4 from './assets/resources/Covenants/Covenant4.vue'
import Cov5 from './assets/resources/Covenants/Covenant5.vue'
import Cov6 from './assets/resources/Covenants/Covenant6.vue'
import Cov7 from './assets/resources/Covenants/Covenant7.vue'
import Cov8 from './assets/resources/Covenants/Covenant8.vue'
import Cov9 from './assets/resources/Covenants/Covenant9.vue'
import Cov10 from './assets/resources/Covenants/Covenant10.vue'
import Cov11 from './assets/resources/Covenants/Covenant11.vue'
import Cov12 from './assets/resources/Covenants/Covenant12.vue'
import Cov13 from './assets/resources/Covenants/Covenant13.vue'
import Cov14 from './assets/resources/Covenants/Covenant14.vue'
import Cov15 from './assets/resources/Covenants/Covenant15.vue'
import Rules from './assets/resources/Rules.vue'
import ByLaws from  './assets/resources/Bylaws.vue'
import ByLaws1 from  './assets/resources/BL/BL1.vue'
import ByLaws2 from  './assets/resources/BL/BL2.vue'
import ByLaws3 from  './assets/resources/BL/BL3.vue'
import ByLaws4 from  './assets/resources/BL/BL4.vue'
import ByLaws5 from  './assets/resources/BL/BL5.vue'
import ByLaws6 from  './assets/resources/BL/BL6.vue'
import Winter from './assets/photos/winter.vue'
import Summer from './assets/photos/summer.vue'
import Nature from './assets/photos/nature.vue'
import People from './assets/photos/people.vue'
import ForSale from './assets/Classifieds/Forsale.vue'
import Misc from './assets/Classifieds/Misc.vue'
import Service from './assets/Classifieds/Services.vue'
import News1 from './assets/News/newsletter1.vue'
import News2 from './assets/News/newsletter2.vue'
import News3 from './assets/News/newsletter3.vue'


export const routes = [
  {path: '/', component: Home},
  {path: '/Gallery', component: Image},
  {path: '/Member', component: Member},
  {path: '/Attention', component: Attention},
  {path: '/Map', component: Maps},
  {path: '/Home/Calender', component: Calender},
  {path: '/Home/Classifies', component: Classified},
  {path: '/Home/Resources', component: Resource},
  {path: '/Home/Resources/Cov1', component: Cov1},
  {path: '/Home/Resources/Cov2', component: Cov2},
  {path: '/Home/Resources/Cov3', component: Cov3},
  {path: '/Home/Resources/Cov4', component: Cov4},
  {path: '/Home/Resources/Cov5', component: Cov5},
  {path: '/Home/Resources/Cov6', component: Cov6},
  {path: '/Home/Resources/Cov7', component: Cov7},
  {path: '/Home/Resources/Cov8', component: Cov8},
  {path: '/Home/Resources/Cov9', component: Cov9},
  {path: '/Home/Resources/Cov10', component: Cov10},
  {path: '/Home/Resources/Cov11', component: Cov11},
  {path: '/Home/Resources/Cov12', component: Cov12},
  {path: '/Home/Resources/Cov13', component: Cov13},
  {path: '/Home/Resources/Cov14', component: Cov14},
  {path: '/Home/Resources/Cov15', component: Cov15},
  {path: '/Home/Resources/Rules', component: Rules},
  {path: '/Home/Resources/ByLaws', component: ByLaws},
  {path: '/Home/Resources/ByLaws/ByLaws1', component: ByLaws1},
  {path: '/Home/Resources/ByLaws/ByLaws2', component: ByLaws2},
  {path: '/Home/Resources/ByLaws/ByLaws3', component: ByLaws3},
  {path: '/Home/Resources/ByLaws/ByLaws4', component: ByLaws4},
  {path: '/Home/Resources/ByLaws/ByLaws5', component: ByLaws5},
  {path: '/Home/Resources/ByLaws/ByLaws6', component: ByLaws6},
  {path: '/Home/Gallery/winter', component: Winter},
  {path: '/Home/Gallery/summer', component: Summer},
  {path: '/Home/Gallery/nature', component: Nature},
  {path: '/Home/Gallery/people', component: People},
  {path: '/Home/Classifieds/ForSale', component: ForSale},
  {path: '/Home/Classifieds/Misc', component: Misc},
  {path: '/Home/Classifieds/Service', component: Service},
  {path: '/Home/News/ToxicWeeds', component: News1},
  {path: '/Home/News/2016_hunting', component: News2},
  {path: '/Home/News/2016_firewood', component: News3},
]
